name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          mkdir package
          pip install --target ./package pandas boto3
          cp -r *.py package/  # Copy your Python files to package folder

      - name: Create Zip file for Lambda function
        run: |
          cd package
          zip -r ../code.zip .

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          command: lambda update-function-code --function-name Jobnet-Web-Scraping --zip-file fileb://code.zip
